What is JUnit?

JUnit is a simple, open source framework to write and run repeatable tests. It is an instance of the xUnit architecture for unit testing frameworks. JUnit features include: Assertions for testing expected results Test fixtures for sharing common test data Test runners for running tests

JUnit was originally written by Erich Gamma and Kent Beck.

https://github.com/junit-team/junit4/wiki/Getting-started


== Hamcrest Library

Hamcrest is a very nice assertion helper that works really well with JUnit. It
helps all assertion easy to write and consistently with `assertThat`.

http://hamcrest.org/JavaHamcrest/

NOTE: JUnit4 includes `hamcrest-core` as dependency and provide `assertThat` wrapper.
But it comes with very little matcher to be useful, so you still need `hamcrest-library`
to be useful.

NOTE: When using with JUnit4 + hamcrest, we need to place hamcrest before JUnit so 
it will resolve correct version.

NOTE: For hamcrest 1.x, you would need to use `hamcrest-library`, while hamcrest 2.x you
use `hamcrest`. 
