= Hello Java

A simple java project to explore the Servlet + JSP/JSTL API

== How to run

1. Package the application with `mvn package`
2. Copy the `target/hello-java-<version>.war` into `$CATALINA_BASE/webapps` directory
3. Start Tomcat server

Or you may also configure your IDE to run this project inside the app server.

== About Tomcat and JSTL

The Tomcat default does not bundle JSTL and application needs to include it.

== About JSP versions

----
Servlet Spec 	JSP Spec 	EL Spec 	WebSocket Spec 	JASPIC Spec 	Apache Tomcat Version 	Latest Released Version 	Supported Java Versions
4.0 	TBD (2.4?) 	TBD (3.1?) 	TBD (1.2?) 	1.1 	9.0.x 	9.0.0.M22 (alpha) 	8 and later
3.1 	2.3 	3.0 	1.1 	1.1 	8.5.x 	8.5.16 	7 and later
3.1 	2.3 	3.0 	1.1 	N/A 	8.0.x (superseded) 	8.0.45 (superseded) 	7 and later
3.0 	2.2 	2.2 	1.1 	N/A 	7.0.x 	7.0.79 	6 and later (7 and later for WebSocket)
2.5 	2.1 	2.1 	N/A 	N/A 	6.0.x 	6.0.53 	5 and later
2.4 	2.0 	N/A 	N/A 	N/A 	5.5.x (archived) 	5.5.36 (archived) 	1.4 and later
2.3 	1.2 	N/A 	N/A 	N/A 	4.1.x (archived) 	4.1.40 (archived) 	1.3 and later
2.2 	1.1 	N/A 	N/A 	N/A 	3.3.x (archived) 	3.3.2 (archived) 	1.1 and later
----

== About `webjars` dependencies

Java Servlet 3.0 will automatically serve any `WEB-INF/resources` files when you include in classpath.
Use this trick, there is a library named https://www.webjars.org/documentation#servlet3[`webjars`] that
bundle man each of the major web css/js files for application uses. We can actually make Java or Maven
dependency then it will automatically server through `/webjars/` prefix path!

We use `bootstrap` and `jQuery` from `webjars` to style our application.
