package com.zemian.hellojava.data.domain;

/**
 * A domain POJO mapped to DB table audit_logs.
 *
 * This class is generated by Zemian's CodeGen Toolbox on Jan 2, 2018.
 */
public class AuditLog {

    private Integer logId; // key
    private String name;
    private String value;
    private java.time.LocalDateTime createdDt;

    public Integer getLogId() {
        return this.logId;
    }
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    public void setValue(String value) {
        this.value = value;
    }
    public java.time.LocalDateTime getCreatedDt() {
        return this.createdDt;
    }
    public void setCreatedDt(java.time.LocalDateTime createdDt) {
        this.createdDt = createdDt;
    }

    @Override
    public String toString() {
        StringBuilder fields = new StringBuilder();
        fields.append("logId=" + getLogId());
        return "AuditLog{" + fields.toString() + "}";
    }
}
