package ${domain.packageName};

/**
 * A domain POJO mapped to DB table ${dbTable.tableName}.
 *
 * This class is generated by Zemian's CodeGen Toolbox on ${todayDt?date}.
 */
public class ${domain.className} {
<#list domain.fields as field>
    <#if field.enumValues??>
    public static enum ${field.enumType} {
        ${field.enumValues?join(", ")};
    }
    </#if>
</#list>

<#list domain.fields as field>
    private ${field.type} ${field.name};<#if field.dbField.key> // key</#if>
</#list>

<#list domain.fields as field>
    public ${field.type} ${field.getterMethodName}() {
        return this.${field.name};
    }
    public void ${field.setterMethodName}(${field.type} ${field.name}) {
        this.${field.name} = ${field.name};
    }
</#list>

    @Override
    public String toString() {
        StringBuilder fields = new StringBuilder();
        <#list domain.fields as field>
        <#if field.dbField.key>
        fields.append("${field.name}=" + ${field.getterMethodName}());
        </#if>
        </#list>
        return "${domain.className}{" + fields.toString() + "}";
    }

    public ${domain.className}() {
    }
}
