What is JUnit 5?

Unlike previous versions of JUnit, JUnit 5 is composed of several different modules from three different sub-projects.

JUnit 5 = JUnit Platform + JUnit Jupiter + JUnit Vintage

The JUnit Platform serves as a foundation for launching testing frameworks on the JVM. It also defines the TestEngine API for developing a testing framework that runs on the platform. Furthermore, the platform provides a Console Launcher to launch the platform from the command line and a JUnit 4 based Runner for running any TestEngine on the platform in a JUnit 4 based environment. First-class support for the JUnit Platform also exists in popular IDEs (see IntelliJ IDEA, Eclipse, NetBeans, and Visual Studio Code) and build tools (see Gradle, Maven, and Ant).

JUnit Jupiter is the combination of the new programming model and extension model for writing tests and extensions in JUnit 5. The Jupiter sub-project provides a TestEngine for running Jupiter based tests on the platform.

JUnit Vintage provides a TestEngine for running JUnit 3 and JUnit 4 based tests on the platform.
1.2. Supported Java Versions

JUnit 5 requires Java 8 (or higher) at runtime. However, you can still test code that has been compiled with previous versions of the JDK.

https://junit.org/junit5/docs/current/user-guide/#overview

== Maven + JUnit5 Setup

----
<build>
	<plugins>
	    <!-- JUnit 5 requires Surefire version 2.22.1 or higher -->
	    <plugin>
	        <artifactId>maven-surefire-plugin</artifactId>
	        <version>2.22.1</version>
	    </plugin>
	</plugins>
</build>
<dependencies>
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>5.4.1</version>
        <scope>test</scope>
    </dependency>
</dependencies>
----

== Examples

https://github.com/junit-team/junit5-samples


== Hamcrest Library

Hamcrest is a very nice assertion helper that works really well with JUnit. It
helps all assertion easy to write and consistently with `assertThat`.

http://hamcrest.org/JavaHamcrest/
