EclipseLink is a powerful and flexible Java persistence framework for storing Java objects in a data store, such as a relational database or a NoSQL database, and for converting Java objects to XML or JSON documents. EclipseLink provides APIs and a run-time environment for implementing the persistence layer of Java Platform, Standard Edition (Java SE platform), and Java Platform, Enterprise Edition (Java EE platform) applications.

https://www.eclipse.org/eclipselink/documentation/2.7/solutions/toc.htm

== Build and Run

  mvn compile
  mvn exec:java -Dexec.mainClass=zemian.eclipselinkstarter.TestRecordMain

== Error: signer information does not match

Answer: The bundled "jakarta.persistence" dep with EclipseLink has problem!
Ensure the standalone dep comes before ElipseLink in Maven pom!

See `pom.xml` and https://stackoverflow.com/questions/45870753/eclipselink-2-7-0-and-jpa-api-2-2-0-signature-mismatch

----
Exception in thread "main" java.lang.SecurityException: class "javax.persistence.PersistenceUtil"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at zemian.eclipselinkstarter.Hello.main(Hello.java:21)

Process finished with exit code 1
----

== How to setup auto scan of Entities

Set `<exclude-unlisted-classes>false</exclude-unlisted-classes>` in `persistence.xml`
