= hello-spring-demo

A simple java project to explore the core Spring library.

== Building and Running a specific DEMO

Most of the sub modules of this projects are specific to exploer certain area of Spring library. We have
moved some common code into `hello-spring-common` that shared for all demos. To run a specific demo,
you first need to install the common module:

  mvn install -DskipTests

Then you may `cd` into any demo to run the main class entry. For example:

  cd hello-spring-demo
  mvn compile exec:java -Dexec.mainClass=com.zemian.hellojava.Hello

To run server:

  mvn compile exec:java -Dexec.mainClass=com.zemian.hellojava.app.SpringServer -Dexec.args=com.zemian.hellojava.Hello\$Config

== Deployment

Build a single executable app jar

  mvn package
  java -jar target/hello-java-1.0-SNAPSHOT-app.jar

== Spring Logging

We use SLF4J via Logback for application logging.

Starting Spring5 it comes with spring-jcl that can auto detects SLF4J and use it. Not need
to exclude JCL explicitly as older version.

== Spring PropertySource Loading

In the demo, we use `CommonConfig` to load "hellojava/app.properties" as main source of properties to
customize the application. See javadoc on `org.springframework.context.annotation.PropertySource` for details.

During testing, use `@TestPropertySource` with "application-test.properties" to override from
main props.


== Spring Dependency Tree

Here is a view of the tree

----
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hello-java 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ hello-java ---
[INFO] com.zemian:hello-java:jar:1.0-SNAPSHOT
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.11:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.1.11:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.22:compile
[INFO] +- org.springframework:spring-context-support:jar:5.0.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.0.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:5.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.0.1.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.0.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-core:jar:5.0.1.RELEASE:compile
[INFO] |     \- org.springframework:spring-jcl:jar:5.0.1.RELEASE:compile
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] \- org.springframework:spring-test:jar:5.0.1.RELEASE:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.560 s
[INFO] Finished at: 2017-11-03T14:26:36-04:00
[INFO] Final Memory: 12M/241M
[INFO] ------------------------------------------------------------------------

----
