package com.zemian.hellojava.service;

import com.zemian.hellojava.data.dao.*;
import com.zemian.hellojava.data.domain.Setting;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * A Service to access Setting.
 *
 * This class is generated by Zemian's CodeGen Toolbox on Jan 1, 2018.
 */
@Service
@Transactional
public class SettingService {
    @Autowired
    private SettingDAO settingDAO;

    public void create(Setting setting) {
        settingDAO.create(setting);
    }

    public void update(Setting setting) {
        settingDAO.update(setting);
    }

    public Setting get(Integer settingId) {
        return settingDAO.get(settingId);
    }

    public void delete(Integer settingId) {
        settingDAO.delete(settingId);
    }

    public boolean exists(Integer settingId) {
        return settingDAO.exists(settingId);
    }

    public List<Setting> findAll() {
        return settingDAO.findAll();
    }

    public PagingList<Setting> find(Paging paging) {
        return settingDAO.find(paging);
    }

    public List<Setting> findByCategory(String category) {
        return settingDAO.findByCategory(category);
    }

    public Map<String, Setting> getCategoryMap(String category) {
        return settingDAO.findByCategory(category).stream().collect(
                Collectors.toMap(Setting::getName, Function.identity()));
    }

    // == Customize
    public boolean exists(String category, String name) {
        return settingDAO.exists(category, name);
    }
}
